-- ── today_muscle_stimulus column on daily_scores ────────────────────────────
-- Stores the raw per-muscle stimulus generated by today's workout.
-- Values are Σ ln(loadRatio × reps × eMod + 1) per muscle group, which is
-- the same science-based per-set stimulus already computed by the scoring
-- engine. This is written fresh each time calculate-scores runs and drives
-- the daily heatmap on the home screen (red intensity = today's effort).
alter table public.daily_scores
  add column if not exists today_muscle_stimulus jsonb not null default '{}'::jsonb;
